"use client";

import { useState } from "react";
import { Check, Copy, ExternalLink } from "lucide-react";
import { parseIntoSegments, InlineSegments } from "@/components/ai-elements/structured-markers";
import type { Report } from "@/lib/reports/report-store";

function parseReportActions(text: string): { cleanText: string } {
  // Strip [ACTION:...], [SUGGEST:...] markers — they're interactive chat elements, not for reports
  const cleanText = text
    .replace(/\[ACTION:[^\]]+\]/g, "")
    .replace(/\[SUGGEST:[^\]]+\]/g, "")
    .trim();
  return { cleanText };
}

function ShareButtons({ reportId }: { reportId: string }) {
  const [copied, setCopied] = useState(false);
  const url = typeof window !== "undefined" ? `${window.location.origin}/r/${reportId}` : "";

  const handleCopy = async () => {
    await navigator.clipboard.writeText(url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShareX = () => {
    const text = encodeURIComponent("Check out this analysis from @ObolAI");
    const shareUrl = encodeURIComponent(url);
    window.open(`https://x.com/intent/tweet?text=${text}&url=${shareUrl}`, "_blank");
  };

  return (
    <div className="flex items-center gap-2">
      <button
        onClick={handleCopy}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium
          bg-muted/50 border border-border text-muted-foreground
          hover:text-foreground hover:bg-muted/80 transition-colors"
      >
        {copied ? <Check className="size-3" /> : <Copy className="size-3" />}
        {copied ? "Copied" : "Copy link"}
      </button>
      <button
        onClick={handleShareX}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium
          bg-muted/50 border border-border text-muted-foreground
          hover:text-foreground hover:bg-muted/80 transition-colors"
      >
        <ExternalLink className="size-3" /> Share on X
      </button>
    </div>
  );
}

export function ReportViewer({ report }: { report: Report }) {
  const { cleanText } = parseReportActions(report.content);
  const segments = parseIntoSegments(cleanText);
  const date = new Date(report.createdAt).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <header className="border-b border-border/50 bg-background/80 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-2xl mx-auto px-4 py-3 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground transition-colors">
            <svg width="20" height="20" viewBox="0 0 32 32">
              <defs>
                <linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%">
                  <stop offset="0%" stopColor="#3b82f6" />
                  <stop offset="100%" stopColor="#8b5cf6" />
                </linearGradient>
              </defs>
              <circle cx="16" cy="16" r="9.5" fill="none" stroke="url(#g)" strokeWidth="3.5" />
              <line x1="4" y1="16" x2="28" y2="16" stroke="url(#g)" strokeWidth="3" strokeLinecap="round" />
            </svg>
            Obol AI
          </a>
          <ShareButtons reportId={report.id} />
        </div>
      </header>

      {/* Content */}
      <main className="max-w-2xl mx-auto px-4 py-8">
        <div className="mb-6">
          <h1 className="text-xl font-semibold text-foreground mb-1">{report.title}</h1>
          <p className="text-xs text-muted-foreground">{date}</p>
        </div>

        <div className="prose-sm">
          <InlineSegments segments={segments} />
        </div>

        {/* CTA */}
        <div className="mt-12 pt-6 border-t border-border/50">
          <div className="flex items-center justify-between">
            <p className="text-xs text-muted-foreground">
              Generated by Obol AI — an agent that pays for intelligence
            </p>
            <a
              href="/chat"
              className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-medium
                bg-gradient-to-r from-blue-500/20 to-cyan-400/20
                border border-blue-500/30 hover:border-blue-500/50
                text-foreground hover:from-blue-500/30 hover:to-cyan-400/30
                transition-all duration-200"
            >
              Try Obol <ExternalLink className="size-3.5" />
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
